sudo: enabled
language: python
python:
  - "3.6"

services:
  - docker

install:
  - pip install flake8

before_script:
  - make flake
  - make version
  - make build

script:
  - make test

after_script:
  - make latest
