sudo: enabled
language: python
python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: build
      install:
        - pip install flake8
      before_script:
        - make flake
        - make version
      script:
        - make build
    - stage: test
      script:
        - make test
      after_script:
        - make latest