sudo: enabled
language: python
python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: Build Docker Image
      install:
        - pip install flake8
      before_script:
        - make flake
        - make version
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make build
        - docker push $DOCKER_USERNAME/flask-ci
      after_script:
        - make latest
    - stage: test
      script:
        - docker pull $DOCKER_USERNAME/flask-ci
        - make test
